# Generated by Django 4.2.23 on 2025-06-24 14:04

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "content",
                    models.JSONField(
                        default=dict,
                        help_text="AI-generated lesson schema: {week, target_phonemes, words[], story, activity}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        help_text="The child this lesson is intended for (used for pre-generation or direct assignment).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="core.child",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Session this lesson is part of, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("completed", models.BooleanField(default=False)),
                (
                    "results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary or full assessment data related to this lesson's completion.",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="core.child",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="curriculum.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Progress Records",
                "ordering": ["child", "lesson", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["child", "lesson"],
                        name="curriculum__child_i_e169f2_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["results"], name="prog_results_gin"
                    ),
                ],
                "unique_together": {("child", "lesson")},
            },
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["child", "-created_at"], name="curriculum__child_i_18dc89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["session", "-created_at"], name="curriculum__session_dbb342_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["content"], name="lesson_content_gin"
            ),
        ),
    ]
