# Generated by Django 4.2.23 on 2025-06-24 14:04

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "overall_score",
                    models.FloatField(help_text="Overall score from 0 to 100"),
                ),
                (
                    "phoneme_scores",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object with phoneme scores, e.g., {'r': 85, 'l': 60}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session", "-timestamp"],
                        name="speech_asse_session_60d767_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["phoneme_scores"], name="assess_phon_scores_gin"
                    ),
                ],
            },
        ),
    ]
