# Generated by Django 4.2.23 on 2025-06-24 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "native_language",
                    models.CharField(
                        help_text="ISO 639-1 language code (e.g., 'en', 'es', 'fa')",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Children",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "livekit_room",
                    models.CharField(
                        help_text="Unique name for the LiveKit room",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the session ended",
                        null=True,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["child", "-started_at"],
                        name="core_sessio_child_i_3e69aa_idx",
                    )
                ],
            },
        ),
    ]
