# Generated by Django 5.2.4 on 2025-09-14 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='user',
        ),
        migrations.AddField(
            model_name='child',
            name='conversation_prompt',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='child',
            name='name',
            field=models.CharField(default='KID', max_length=128),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SessionAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_vocalizations', models.PositiveIntegerField(default=0)),
                ('assistant_responses', models.PositiveIntegerField(default=0)),
                ('avg_child_utterance_length', models.FloatField(blank=True, help_text='Average words per child utterance', null=True)),
                ('unique_child_words', models.PositiveIntegerField(default=0)),
                ('encouragements_given', models.PositiveIntegerField(default=0)),
                ('child_to_ai_ratio', models.FloatField(blank=True, help_text='Ratio of child utterances to AI responses', null=True)),
                ('topics_detected', models.JSONField(blank=True, default=list, help_text='List of topics covered (e.g., animals, colors)')),
                ('best_utterance', models.TextField(blank=True, help_text='The longest or most accurate phrase by the child')),
                ('conversation_summary', models.TextField(blank=True, help_text='Short narrative summary of the session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(help_text='The session this analytics data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.session')),
            ],
        ),
    ]
